### ISSUE TITLE
Node.js + browser sync on different ports

### ISSUE THREAD

**Issue by admdh** [schmich/connect-browser-sync#12]
Is there any way to run both node.js and browser sync at the same time on different ports?

**Comment by schmich** [comment]
Yes, you can specify the BrowserSync port as part of its options. See http://www.browsersync.io/docs/options/#option-port

For example, you can initialize BrowserSync with:

```
var browserSync = require('browser-sync');
var bs = browserSync({ port: 3030 });
app.use(require('connect-browser-sync')(bs));
```

**Comment by admdh** [comment]
i'm currently using this kind of setup of node.js but if i specify port in bs variable nothing happens.
and if i add proxy it tries to load page but it takes forever. may be I'm missing something, could you please help me?

var express = require('express');
var http = require('http');
var routes = require('./bin/routes/routes');
var harp = require('harp');
var jade = require('jade');

var open = require('open');

var app = express();

var port = 8080;
var host = 'http://localhost:';

var webRootPath = "/webroot";

app.set('views', __dirname + webRootPath);
app.set('view engine', 'jade');


if(app.get('env') == 'development'){
	var browserSync = require('browser-sync');
	var bs = browserSync({
		files:[
			__dirname + webRootPath + '/**/**/**/*.jade',
			__dirname + webRootPath + '/**/**/**/*.scss',
			__dirname + webRootPath + '/**/*.js'
		],
		port: 3030,
		logSnippet: false
	});
	app.use(require('connect-browser-sync')(bs));
}

app.get('./', routes.index);

app.use(express.static(__dirname + webRootPath));
app.use(harp.mount(__dirname + webRootPath));

http.createServer(app).listen(port, function(){
	console.log('Listening: ' + host + port);
});

open(host + port);

**Comment by schmich** [comment]
I used the example app I created [here](https://github.com/schmich/connect-browser-sync/tree/master/example), and when I changed the `port` setting in the BrowserSync options and restarted the app, I noticed that sometimes the response would be cached, so the BrowserSync port in the injected script was incorrect.

Try doing a forceful refresh in your browser (Ctrl+F5 or Command+Shift+R) after setting the `port` option and restarting your app. If you "View Source" on your page, you should see the BrowserSync `<script>` tag with the correct port number. In my case, with port 8000, it is:

```html
  <script type='text/javascript' id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://HOST:8000/browser-sync/browser-sync-client.2.7.2.js'><\/script>".replace("HOST", location.hostname));
//]]></script>
```

If that still doesn't work, let me know what package versions you're using. I'm using:

- `browser-sync: 2.7.21`
- `connect-browser-sync: 2.0.1`
- `express: 4.12.4`

**Comment by schmich** [comment]
I'm closing this issue, but let me know if you need any more help here.
