### ISSUE TITLE
Error browserSync.events.on

### ISSUE THREAD

**Issue by hydrotik** [schmich/connect-browser-sync#9]
```
/node_modules/connect-browser-sync/index.js:9
  browserSync.events.on('init', function(config) {
                    ^
TypeError: Cannot read property 'on' of undefined
    at injectBrowserSync (/node_modules/connect-browser-sync/index.js:9:21)
    at Object.<anonymous> (/app.js:32:42)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/bin/www:6:11)
    at Module._compile (module.js:460:26)
[gulp] [nodemon] app crashed - waiting for file changes before starting...
```
Using:
```javascript
// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'hbs');

// uncomment after placing your favicon in /public
//app.use(favicon(__dirname + '/public/favicon.ico'));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
if (app.get('env') == 'development') {
  var browserSync = require('browser-sync');
  var bs = browserSync.init([], {});
  app.use(require('connect-browser-sync')(bs));
}
app.use(express.static(path.join(__dirname, 'public')));



app.use('/', routes);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
    var err = new Error('Not Found');
    err.status = 404;
    next(err);
});
```

**Comment by hasalex** [comment]
Same error here. Using 
   "connect-browser-sync": "~1.0.2"
and 
    "browser-sync": "~2.2.1"

Is connect-browser-sync compatible with browser-sync 2 ?

**Comment by schmich** [comment]
Apologies, I had some personal things come up. I will be able to look at
this issue this weekend.

**Comment by hydrotik** [comment]
Thanks!

**Comment by hydrotik** [comment]
Also do you have some suggestions on how this will work when it is being proxies? I would guess that this would allow to avoid needing to use the proxy setup? Would be great if there were some examples of this using an express generated app. Thanks again.

**Comment by schmich** [comment]
Sorry for the terrible delay, but `connect-browser-sync` should be fully compatible with BrowserSync 2.x now.

@hydrotik Yes, the purpose of this is to avoid needing a proxy at all since it's a plugin in connect that is doing the script tag injection. You can see example code in [README.md](https://github.com/schmich/connect-browser-sync/blob/master/README.md) or in the self-contained app in the [example folder](https://github.com/schmich/connect-browser-sync/tree/master/example).

**Comment by hydrotik** [comment]
Thanks!
